version: '3'

volumes:
  keycloak-db-data:
    driver: local

services:
  postgres:
    image: postgres:16.3
    container_name: postgres_keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: my_keycloak
      POSTGRES_PASSWORD: secret123
  keycloak:
    build: ./keycloak/
    container_name: keycloak
    environment:
      #Admin Credentials
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_URL: 'jdbc:postgresql://postgres/keycloak'
      KC_DB_USERNAME: my_keycloak
      KC_DB_PASSWORD: secret123
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: localhost
      PROXY_ADDRESS_FORWARDING: "true"
    command:
      - "-v start-dev --optimized"
    ports:
      - 8443:8443
      - 8080:8080
    depends_on: 
      - postgres_keycloak
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
