namespace PSuite.Modules.Configuration.Core.Entities;

internal class Employee
{
    public Guid Id { get; set; }
    public required string FirstName { get; set; }
    public required string LastName { get; set; }
    
    //NOTE: "foreign" id generated by Keycloak
    public Guid UserId { get; set; }
    public Hotel? Hotel { get; set; }
}
