using System.Diagnostics.CodeAnalysis;

namespace PSuite.Modules.Configuration.Core.Entities;

internal class Employee
{
    public Guid Id { get; init; }
    public required string FirstName { get; set; }
    public required string LastName { get; set; }
    
    //NOTE: "foreign" id generated by Keycloak
    public Guid UserId { get; set; }
    public Hotel? Hotel { get; set; }

    private Employee() { }

    [SetsRequiredMembers]
    public Employee(string firstName, string lastName, Hotel? hotel = null)
    {
        Id = Guid.CreateVersion7();
        FirstName = firstName;
        LastName = lastName;
        Hotel = hotel;
    }
}
